# Generated by Django 4.2.2 on 2023-08-01 08:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.IntegerField(verbose_name=api.models.User_Model)),
                ('to_account', models.IntegerField(verbose_name=api.models.User_Model)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=15)),
                ('User_IIN', models.IntegerField(max_length=12, unique=True)),
                ('All_money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
