# Generated by Django 4.2.2 on 2023-08-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='All_money',
            field=models.FloatField(default=0),
        ),
    ]
